### ISSUE TITLE
Is there any way to export the whole world as GeoJSON?

### ISSUE THREAD

**Issue by ofou** [haoliangyu/boundary.now#19]
I wonder if there's any way to do that. Awesome tool BTW!

**Comment by haoliangyu** [comment]
No, this tool downloads the boundary from a geocoding result. It is not a batch downloader with filters.

Programmatically extracting boundaries at world scale could be a non-trival task, depending on the level of details you need. For general research or catography need, I would recommand using pre-built collections from https://www.naturalearthdata.com.

**Comment by ofou** [comment]
Thanks for the answer @haoliangyu! 

I'm actually looking for just country-level boundaries. It seems that [Natural Earth Data](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/) will do the trick, but I think your tool for each 200+ countries could provide ~1m borders, I think 10x better accuracy than Natural Earth Data.
